image: node:latest

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"

deploy_dev:
  stage: deploy
  script:
    - echo "Deploy to dev server"
  environment:
    name: staging
    url: https://dev.nadespots.com
  only:
  - master
